@startuml
'https://plantuml.com/sequence-diagram

autonumber

EngineService -> EngineService: run
EngineService -> DecisionFlow: run
DecisionFlow -> DecisionFlow: getStartNode
DecisionFlow -> DecisionFlow: parseNode
DecisionFlow -> FlowNode: parse
FlowNode -> RulesetNode: parse
RulesetNode -> PipelineContext: getFeatures
RulesetNode -> RulesetNode: getRules
RulesetNode -> Rule: parse
Rule -> Rule: getConditions
Rule -> IFeature: compare
Rule -> Decision: getLogic
Rule -> Operator: evaluate
Rule <-- Rule: Output
RulesetNode <-- Rule: Output
FlowNode <-- RulesetNode: NodeResult
DecisionFlow <-- FlowNode: NodeResult
DecisionFlow -> DecisionFlow: NodeResult
DecisionFlow -> PipelineContext: addNodeResult
DecisionFlow <-- DecisionFlow: put resultMap（nextNode以及gotoNext标识）

@enduml