@startuml
'https://plantuml.com/sequence-diagram

autonumber
hide footbox

业务前端 -> 业务后端: 配置业务规则
业务后端 -> 规则引擎: 注册规则
规则引擎 -> 规则引擎: 翻译规则并入库
业务后端 <-- 规则引擎: 返回rulesetId
业务后端 -> 业务后端: 保存rulesetId和业务对应关系

业务前端 -> 业务后端: 执行需要触发的业务动作
业务后端 -> 业务后端: 查询rulesetId
业务后端 -> 规则引擎: 根据rulesetId获取规则集详情
业务后端 <-- 规则引擎: 返回规则集详情
业务后端 -> 业务后端: 查询业务数据
业务后端 -> 业务后端: 执行规则
业务前端 <-- 业务后端: 返回执行结果

@enduml